const BlogData = [
  {
    id: 1,
    date: "January 01, 2020",
    catgeory: "Business ",
    title: "A luxorious cozy hotel",
    cover: "/images/singlepage/blog-1.jpg",
    para: "",
    desc: ""
  },
  {
    id: 2,
    date: "January 15, 2021",
    catgeory: "Traveling",
    title: "Beautiful relaxing Hotel",
    cover: "/images/singlepage/blog-2.jpg",
    para: "",
    desc: ""
  },
  {
    id: 3,
    date: "January 21, 2018",
    catgeory: "Tourist",
    title: "Comfy gorgeous hotel",
    cover: "/images/singlepage/blog-3.jpg",
    para: "",
    desc: "",
  },
  {
    id: 4,
    date: "January 30, 2019",
    catgeory: "Tourist",
    title: "One of a kind",
    cover: "/images/singlepage/blog-4.jpg",
    para: "",
    desc: "",
  },
  {
    id: 5,
    date: "January 10, 2022",
    catgeory: "Tourist",
    title: "Stunner",
    cover: "/images/singlepage/blog-5.jpg",
    para: "",
    desc: "",
  },
  {
    id: 6,
    date: "January 18, 2021",
    catgeory: "Tourist",
    title: "100",
    cover: "/images/singlepage/blog-6.jpg",
    para: "",
    desc: "",
  },
  {
    id: 6,
    date: "January 12, 2014",
    catgeory: "Tourist",
    title: "Peace of mind",
    cover: "/images/singlepage/blog-1.jpg",
    para: "",
    desc: "",
  },
  {
    id: 7,
    date: "January 30, 2019",
    catgeory: " Tourist",
    title: "Does it get any better",
    cover: "/images/singlepage/blog-4.jpg",
    para: "",
    desc: "",
  },
  {
    id: 8,
    date: "January 10, 2022",
    catgeory: "Tourist",
    title: "what a hotel",
    cover: "/images/singlepage/blog-5.jpg",
    para: "",
    desc: "",
  },
]

export default BlogData
